### ISSUE TITLE
Undesirable Links and tings

### ISSUE THREAD

**Issue by RobertPower** [nathanpower/wordflow-site#26]
**Blog Creation Section**
- [x] Mark Rowe Link should go to my blog page with the search heading for Self Help blogs only
- [x] ZF Link should go to my blog page showing only Glazing Industry Links

**Copy Editing Section**
- [x] 2Trust link should go here: http://2trust.nl/about-us/financial-outsourcing/?lang=en

**Social Media section**
- [x] ZF Page should go to ZF home page (bottom by SM links  if possible)
- [x] Facebook section should bring to ZF facebook
- [x] Adwords section has no pic, I would like a screenshot of the google adwords result for ZF Ireland with snippets etc. The link should be a search for ZF Ireland maybe?

Also:
- [x] No about page
- [x] Can we have testimonials button which jumps to scroller for now and then when I compile some more we can have a page?
- [x] Maybe some clever stock image for Writer for hire page, typwriter, or stylus, or some such.
- [x] Everything got rearranged so that website copy is no longer first on home page or drop down? It's the central service really.

**Comment by nathanpower** [comment]
whoops, I broke the ordering of services along the way, must write some tests for that build, should be sorted now

**Comment by nathanpower** [comment]
All changes deployed @RobertPower, can you have a look and close this if all is ok?
