### ISSUE TITLE
Build is failing - Module not found error

### ISSUE THREAD

**Issue by suryapandian** [nathanpower/wordflow-site#56]
I tried to clone the repository and start the server locally 
I have set the environment variable as `SITE_ROOT as ./src`
But I am getting the below error

```
[❌] Application bundling failed
  Error: multi react-hot-loader/patch ../lib/bootstrapPlugins.js ../lib/bootstrapTemplates.js index.js
  Module not found: Error: Can't resolve 'index.js' in '/Users/suryapandian/repo/drona/wordflow-site/node_modules/react-static/node_modules'
   @ multi react-hot-loader/patch ../lib/bootstrapPlugins.js ../lib/bootstrapTemplates.js index.js main[3]
  multi (webpack)-dev-server/client?http://localhost:3001 (webpack)/hot/only-dev-server.js react-hot-loader/patch ../lib/bootstrapPlugins.js ../lib/bootstrapTemplates.js index.js
  Module not found: Error: Can't resolve 'index.js' in '/Users/suryapandian/repo/drona/wordflow-site/node_modules/react-static/node_modules'
   @ multi (webpack)-dev-server/client?http://localhost:3001 (webpack)/hot/only-dev-server.js react-hot-loader/patch ../lib/bootstrapPlugins.js ../lib/bootstrapTemplates.js index.js main[5] 

```

Please do let me know what I am missing.

The website, design, flow and feel is superb!!!

**Comment by nathanpower** [comment]
Should be fixed by https://github.com/nathanpower/wordflow-site/commit/1dbac106be14e9e4bd3e5c244bb18c46b2cd37f4

Note `SITE_ROOT` is not needed when running locally, and should be the hostname when deploying somewhere that doesn't set that automatically.

**Comment by nathanpower** [comment]
@suryapandian let me know if this works for you and I will close this?

Also, if you use a fork of this repo for a public site, including a small credit / link to `workflow.ie` in the footer would be appreciated!

Thanks

**Comment by suryapandian** [comment]
Yes, @nathanpower your fix has solved the error, thanks a lot.
I love the UI and UX, I will most certainly give credit in the footer if we go live with this.
Thanks a lot again, you can close this issue :)

**Comment by suryapandian** [comment]
Actually this design exactly meets our requirement, so I am pretty confident that we will be using it so thanks in advance, I will let you know and make sure to add the credit :)
