### ISSUE TITLE
Unable to deploy on production in cloud services

### ISSUE THREAD

**Issue by suryapandian** [nathanpower/wordflow-site#57]
Invalid Issue

**Comment by nathanpower** [comment]
Hey @suryapandian, it's been a while since I set up Netlify, but it's possible I set the `SITE_ROOT` environment variable manually there (not automatically like the docs say).

**Comment by nathanpower** [comment]
My `SITE_ROOT` looks like this (from Netlify dashboard):

![Screenshot 2020-03-11 at 14 23 14](https://user-images.githubusercontent.com/13329684/76427227-f2a5e980-63a3-11ea-8571-47a8779ee532.png)

**Comment by suryapandian** [comment]
Thank you by setting the SITE_ROOT with the `https://www` it worked in Netlify.
In Heroku too with the help of a friend successfully ran the website with the build.

Thanks

**Comment by nathanpower** [comment]
Great, will update readme
